apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-s1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-s1
  template:
    metadata:
      labels:
        app: myapp-s1
    spec:
      containers:
        - name: mycontainer-s1
          image: nginx:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-s1
  labels:
    run: myapp-s1
spec:
  type: ClusterIP
  selector:
    app: myapp-s1
  ports:
    - port: 80
      protocol: TCP
